# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Notification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12Notification.proto\"\x07\n\x05void2\"\x18\n\x05Notif\x12\x0f\n\x07message\x18\x01 \x01(\t2*\n\x0cNotification\x12\x1a\n\x06Notif1\x12\x06.Notif\x1a\x06.void2\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Notification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOID2']._serialized_start=22
  _globals['_VOID2']._serialized_end=29
  _globals['_NOTIF']._serialized_start=31
  _globals['_NOTIF']._serialized_end=55
  _globals['_NOTIFICATION']._serialized_start=57
  _globals['_NOTIFICATION']._serialized_end=99
# @@protoc_insertion_point(module_scope)
